### ISSUE TITLE
Calling Utils function creating issue for nested expando object

### ISSUE THREAD

**Issue by aditya4903** [microsoft/RulesEngine#378]
**ERROR: Enum type 'Biller.MasterDocuments.Customer' not found**

Below is the input data (input1)
[jsonformatter.txt](https://github.com/microsoft/RulesEngine/files/9225757/jsonformatter.txt)

Expression:
utils.CheckContains(new string[]{ "Sachin", "SAMPLE A SAMPLE"},String(input1.Biller.MasterDocuments.Customer.CustomerName)) == true

**Util class:**

    internal class TestInstanceUtils
    {
        public bool CheckContains(string[] strarr,string str)
        {
            if (strarr.Contains(str))
                return true;
            else
                return false;
        
        }
    }

**RuleEngine:**

   var utils = new TestInstanceUtils();
    List<RuleResultTree> resultList =
                                bre.ExecuteAllRulesAsync("inputWorkflow", new RuleParameter("input1", obj), new RuleParameter("utils", utils)).Result;

**Exception Stack Trace:**

   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAsEnum(String id)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression expression)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArguments()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArgumentList()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseTypeAccess(Type type)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimaryStart()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArguments()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArgumentList()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression expression)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor)
   at RulesEngine.ExpressionBuilders.RuleExpressionParser.Parse(String expression, ParameterExpression[] parameters, Type returnType) in D:\RuleEngineRepo\src\RulesEngine\ExpressionBuilders\RuleExpressionParser.cs:line 41
   at RulesEngine.ExpressionBuilders.RuleExpressionParser.<>c__DisplayClass6_0`1.<Compile>b__0() in D:\RuleEngineRepo\src\RulesEngine\ExpressionBuilders\RuleExpressionParser.cs:line 56
   at RulesEngine.HelperFunctions.MemCache.GetOrCreate[T](String key, Func`1 createFn, Nullable`1 expiry) in D:\RuleEngineRepo\src\RulesEngine\HelperFunctions\MemCache.cs:line 74
   at RulesEngine.ExpressionBuilders.RuleExpressionParser.Compile[T](String expression, RuleParameter[] ruleParams) in D:\RuleEngineRepo\src\RulesEngine\ExpressionBuilders\RuleExpressionParser.cs:line 53
   at RulesEngine.ExpressionBuilders.LambdaExpressionBuilder.BuildDelegateForRule(Rule rule, RuleParameter[] ruleParams) in D:\RuleEngineRepo\src\RulesEngine\ExpressionBuilders\LambdaExpressionBuilder.cs:line 30

**Comment by abbasc52** [comment]
Hi @aditya4903 are you using a strong typed object or a dynamic object? and in case you are using a strong typed object , can u share the contract?

**Comment by aditya4903** [comment]
Hi @abbasc52,
Earlier I was using the below
 dynamic dyn = JsonConvert.DeserializeObject<ExpandoObject>(jsonText);

            var input1 = new dynamic[]
              {
                    dyn
              };
 
 Then it has given an error.
 
 Now, I've changed it to the below code and it is working fine.
 
            dynamic dyn = JsonConvert.DeserializeObject<ExpandoObject>(jsonText);

            dynamic input1 = new ExpandoObject();
            input1.Property1 = dyn;
               

Thanks for your response.

**Comment by abbasc52** [comment]
JsonConvert converts object to JObject by default . If you want to get expandoObject, you might want to try using ExpandoObjectConvertor.
e.g.
https://github.com/microsoft/RulesEngine/blob/77750ae0b4eeddacedd4f45e7719545e0ea9a10f/test/RulesEngine.UnitTest/BusinessRuleEngineTest.cs#L816-L821

Can you try this and let me know it works for you?

**Comment by vprabhu81** [comment]
A follow up question on this, I too wanted a non static util class for additional check however when I pass it as rule parameters like mentioned in the question it doesnt work and gives me exception
Exception while parsing expression `Utils.CheckContains("1","1")` - Unknown identifier 'Utils'

**Comment by aditya4903** [comment]
Resolved
