### ISSUE TITLE
Error with EFDemo: Rule config file is not present for the Discount workflow

### ISSUE THREAD

**Issue by brianwolfe-cgi** [microsoft/RulesEngine#420]
Running the EFDemo from the main branch results in the following error while all other demos work fine.

**Rule config file is not present for the Discount workflow**

Running EFDemo....
Unhandled exception. System.ArgumentException: Rule config file is not present for the Discount workflow
   at RulesEngine.RulesEngine.ValidateWorkflowAndExecuteRule(String workflowName, RuleParameter[] ruleParams) in C:\src\RuleEngineDemo\MicrosoftRulesEngine\src\RulesEngine\RulesEngine.cs:line 264
   at RulesEngine.RulesEngine.ExecuteAllRulesAsync(String workflowName, RuleParameter[] ruleParams) in C:\src\RuleEngineDemo\MicrosoftRulesEngine\src\RulesEngine\RulesEngine.cs:line 106
   at RulesEngine.RulesEngine.ExecuteAllRulesAsync(String workflowName, Object[] inputs) in C:\src\RuleEngineDemo\MicrosoftRulesEngine\src\RulesEngine\RulesEngine.cs:line 93
   at DemoApp.EFDemo.Run() in C:\src\RuleEngineDemo\MicrosoftRulesEngine\demo\DemoApp\EFDemo.cs:line 60
   at DemoApp.Program.Main(String[] args) in C:\src\RuleEngineDemo\MicrosoftRulesEngine\demo\DemoApp\Program.cs:line 13

C:\src\RuleEngineDemo\MicrosoftRulesEngine\demo\DemoApp\bin\Debug\net6.0\DemoApp.exe (process 40708) exited with code -532462766.

**Comment by asulwer** [comment]
@brianwolfe-cgi  fyi: its in the Workflows folder which is a sub directory of the DemoApp directory.

changing the project setting for this file to move upon compilation to the output folder wouldn't require code to be changed.

**Comment by subrata1106** [comment]
Most likely you have changed "WorkflowName": "<workflow name>" in the Discount.json file to something else. The workflow name must match the line in the code 
List<RuleResultTree> resultList = bre.ExecuteAllRulesAsync("<workflow name>", input).Result;

**Comment by abbasc52** [comment]
Closing due to inactivity
